format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
[\\[](bold blue)$username[@](bold yellow)$hostname[\\]](bold blue)$character
"""

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold blue"
format = "[$path]($style) [$read_only]($read_only_style)"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind \]]($style) )'
ahead = " ${count}⇡"
behind = " ${count}⇣"
conflicted = " ${count}="
untracked = " ${count}?"
stashed = " ${count}?"
modified = " ${count}!"
staged = " ${count}+"
renamed = " ${count}>>"
deleted = " ${count}✘"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold white)"
disabled = false

[character]
#success_symbol = "[\\[](blue)[balrrach][@](yellow)[laptop][\\](blue)]"
success_symbol = "[ ➜](bold green)"
error_symbol = "[ ➜](bold red)"
